apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: >-
      {"input":{"containers":[{"name":"scooters-app-1"}]},"output":{"containers":[{"limits":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"scooters-app-1"}]},"modified":true}
    autopilot.gke.io/warden-version: 2.7.52
  labels:
    app: scooter-web-02
  managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      manager: GoogleCloudConsole
      operation: Update
      time: '2024-03-25T11:17:27Z'
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2024-03-25T11:17:31Z'
  name: scooter-web-02
  namespace: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: scooter-web-02
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scooter-web-02
    spec:
      containers:
        - image: gcr.io/smooth-calling-381811/github.com/tomacgg/scooters-app
          imagePullPolicy: IfNotPresent
          name: scooters-app-1
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/arch
          operator: Equal
          value: amd64
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: scooter-web-02
  managedFields:
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      manager: GoogleCloudConsole
      operation: Update
      time: '2024-03-25T11:17:27Z'
    - apiVersion: autoscaling/v2
      fieldsType: FieldsV1
      manager: vpa-recommender
      operation: Update
      subresource: status
      time: '2024-03-25T11:18:44Z'
  name: scooter-web-02-hpa-0apl
  namespace: green
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scooter-web-02
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: scooter-web-02
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      manager: GoogleCloudConsole
      operation: Update
      time: '2024-03-25T11:17:34Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      manager: cloud-controller-manager
      operation: Update
      subresource: status
      time: '2024-03-25T11:18:08Z'
  name: scooter-web-02-service
  namespace: green
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.231.108
  clusterIPs:
    - 34.118.231.108
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30281
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: scooter-web-02
  sessionAffinity: None
  type: LoadBalancer
